# Generated by Django 4.1.2 on 2023-03-27 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=35)),
                ('photo_main', models.ImageField(blank=True, default='defaults/no-image.jpeg', null=True, upload_to='listings/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, default='defaults/no-image.jpeg', null=True, upload_to='listings/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, default='defaults/no-image.jpeg', null=True, upload_to='listings/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, default='defaults/no-image.jpeg', null=True, upload_to='listings/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, default='defaults/no-image.jpeg', null=True, upload_to='listings/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, default='defaults/no-image.jpeg', null=True, upload_to='listings/%Y/%m/%d/')),
                ('state', models.CharField(choices=[('FC', 'abuja'), ('AB', 'abia'), ('AD', 'adamawa'), ('AK', 'akwa'), ('AN', 'anambra'), ('BA', 'bauchi'), ('BY', 'bayelsa'), ('BE', 'benue'), ('BO', 'borno'), ('CR', 'cross river'), ('DE', 'delta'), ('EB', 'ebonyi'), ('ED', 'edo'), ('EK', 'ekiti'), ('EN', 'enugu'), ('GO', 'gombe'), ('IM', 'imo'), ('JI', 'jigawa'), ('KD', 'kaduna'), ('KN', 'kano'), ('KT', 'katsina'), ('KE', 'kebbi'), ('KO', 'kogi'), ('KW', 'kwara'), ('LA', 'lagos'), ('NA', 'nassarawa'), ('NI', 'niger'), ('OG', 'ogun'), ('ON', 'ondo'), ('OS', 'osun'), ('OY', 'oyo'), ('PL', 'plateaue'), ('RI', 'rivers'), ('SO', 'sokoto'), ('TA', 'taraba'), ('YO', 'yobe'), ('ZA', 'zamfara')], default=None, max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('agent_fee', models.IntegerField(default=0)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('new_house', models.BooleanField(default=False)),
                ('gated_compound', models.BooleanField(default=False)),
                ('running_water', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='listingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
